#!/usr/bin/env python3
"""
Generate .env file for local development from Terraform outputs.

This script reads Terraform outputs and creates a .env file with all
required configuration for running the Vanna AI app locally.
"""
import json
import subprocess
import sys
from pathlib import Path

def get_terraform_output(output_name: str) -> str:
    """Get a Terraform output value."""
    try:
        result = subprocess.run(
            ["terraform", "output", "-raw", output_name],
            cwd=Path(__file__).parent.parent / "terraform",
            capture_output=True,
            text=True,
            check=True
        )
        value = result.stdout.strip()
        return value if value else None
    except subprocess.CalledProcessError:
        # Output might not exist, return None
        return None
    except FileNotFoundError:
        print("Error: terraform command not found. Make sure Terraform is installed.", file=sys.stderr)
        return None

def main():
    """Generate .env file from Terraform outputs."""
    print("Generating .env file from Terraform outputs...")
    print()
    
    # Get values from Terraform
    terraform_dir = Path(__file__).parent.parent / "terraform"
    
    if not (terraform_dir / "terraform.tfstate").exists():
        print("Error: Terraform state file not found. Please run 'terraform apply' first.", file=sys.stderr)
        sys.exit(1)
    
    # Get region from terraform.tfvars first, then try output
    region = "us-east-1"  # default
    tfvars_path = terraform_dir / "terraform.tfvars"
    if tfvars_path.exists():
        with open(tfvars_path, 'r') as f:
            for line in f:
                if line.strip().startswith('region'):
                    value = line.split('=', 1)[1].strip().strip('"').strip("'")
                    if value:
                        region = value
                        break
    
    # Get configuration values from Terraform outputs
    glue_database = get_terraform_output("glue_database_name")
    athena_workgroup = get_terraform_output("athena_workgroup_name")
    athena_s3_staging = get_terraform_output("athena_query_result_location")
    
    if not all([glue_database, athena_workgroup, athena_s3_staging]):
        print("Error: Could not get all required Terraform outputs.", file=sys.stderr)
        print("Make sure Terraform has been applied and outputs are available.", file=sys.stderr)
        print()
        print("You can also manually create .env file with these variables:")
        print("  AWS_REGION")
        print("  ATHENA_DATABASE")
        print("  ATHENA_WORKGROUP")
        print("  ATHENA_S3_STAGING")
        print("  LLM_API_KEY")
        sys.exit(1)
    
    # Get LLM API key from terraform.tfvars (if available)
    llm_api_key = None
    if tfvars_path.exists():
        with open(tfvars_path, 'r') as f:
            for line in f:
                if line.strip().startswith('llm_api_key'):
                    # Extract value (handles both quoted and unquoted)
                    value = line.split('=', 1)[1].strip().strip('"').strip("'")
                    if value and not value.startswith('sk-xxxxx'):
                        llm_api_key = value
                        break
    
    if not llm_api_key:
        print("Warning: LLM_API_KEY not found in terraform.tfvars")
        print("You'll need to set it manually in the .env file")
        print()
    
    # Create .env file content
    env_content = f"""# Local Development Environment Configuration
# Generated by setup_local_env.py
# This file is gitignored - do not commit it

# AWS Configuration
AWS_REGION={region}

# Athena Configuration
ATHENA_DATABASE={glue_database}
ATHENA_WORKGROUP={athena_workgroup}
ATHENA_S3_STAGING={athena_s3_staging}

# Glue Data Catalog Configuration
GLUE_DATABASE={glue_database}

# LLM Configuration
# Set your API key here or use environment variable
LLM_API_KEY={llm_api_key or 'YOUR_API_KEY_HERE'}
LLM_PROVIDER=openai
# LLM_MODEL=gpt-4  # Optional, will use default if not set

# Application Settings
AUTO_TRAIN=true
"""
    
    # Write .env file
    env_path = Path(__file__).parent.parent / ".env"
    with open(env_path, 'w') as f:
        f.write(env_content)
    
    print(f"✓ Created .env file at: {env_path}")
    print()
    print("Configuration:")
    print(f"  AWS_REGION: {region}")
    print(f"  ATHENA_DATABASE: {glue_database}")
    print(f"  ATHENA_WORKGROUP: {athena_workgroup}")
    print(f"  ATHENA_S3_STAGING: {athena_s3_staging}")
    print(f"  LLM_API_KEY: {'***SET***' if llm_api_key else 'NOT SET - Please update .env file'}")
    print()
    
    if not llm_api_key:
        print("⚠ IMPORTANT: Please update the LLM_API_KEY in .env file before running the app")
        print()
    
    print("Next steps:")
    print("  1. Review and update .env file if needed")
    print("  2. Install dependencies: pip install -r requirements.txt")
    print("  3. Run the app: python app.py")
    print("  4. Or use: uvicorn app:app --reload --host 0.0.0.0 --port 8000")

if __name__ == "__main__":
    main()
